SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CarType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CarBrandID] int NOT NULL,	
	[Name] NVARCHAR(120) NOT NULL,
	[Status_Id] int NOT NULL,
 CONSTRAINT [PK_Auto] PRIMARY KEY CLUSTERED 
(
	[CarBrandID] ASC,
	[Status_Id] ASC	
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO